---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-provider-aws
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::310924428330:role/crossplane
spec:
  podSecurityContext:
    fsGroup: 2000
  resources:
    limits:
      cpu: 1
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  ports:
    - containerPort: 8080
      name: metrics
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-aws
spec:
  package: "crossplanecontrib/provider-aws:v0.33.0"
  controllerConfigRef:
    name: crossplane-provider-aws
