---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 10m
  chart:
    spec:
      chart: crossplane
      version: "1.10.1"
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: crossplane-system
  values:
    metrics:
      enabled: true
