apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: cert-manager
spec:
  forProvider:
    policyArnRef:
      name: cert-manager
    roleNameRef:
      name: cert-manager
  providerConfigRef:
    name: crossplane-provider-aws
