---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: otel-collector
spec:
  interval: 2m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.22.1"
      sourceRef:
        kind: HelmRepository
        name: otel-collector
        namespace: otel-collector
  values:
    mode: deployment
    config:
      receivers:
        zipkin:
          endpoint: 0.0.0.0:9411
      exporters:
        otlphttp:
          endpoint: https://tempo-eu-west1.grafana.net
          headers:
            Authorization: Basic ${grafana_cloud_tempo_credentials}
      service:
        pipelines:
          traces:
            receivers: [zipkin]
            exporters: [otlphttp]