---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: otel-collector
  namespace: otel-collector
spec:
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
  interval: 2m
