---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail  
  namespace: loki
spec:
  interval: 2m
  chart:
    spec:
      chart: promtail
      version: "6.2.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki