apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: otel-collector
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/otel-collector/installation
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: grafanacloud
        optional: false