---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio
spec:
  interval: 2m
  chart:
    spec:
      chart: base
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio
spec:
  interval: 2m
  chart:
    spec:
      chart: istiod
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 2m
  chart:
    spec:
      chart: gateway
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio