---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 2m
  chart:
    spec:
      chart: base
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 2m
  chart:
    spec:
      chart: istiod
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    pilot:
      traceSampling: 100
    global:
      tracer:
        zipkin:
          address: otel-collector.otel-collector.svc:9411
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 2m
  chart:
    spec:
      chart: gateway
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system