---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed  
  namespace: kubed
spec:
  interval: 2m
  chart:
    spec:
      chart: kubed
      version: "v0.13.2"
      sourceRef:
        kind: HelmRepository
        name: kubed
        namespace: kubed
