---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 2m
  chart:
    spec:
      chart: cert-manager
      version: "v1.10.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  values:
    installCRDs: true
